### ISSUE TITLE
Usage of DateTime class

### ISSUE THREAD

**Issue by s0nic7** [EasyPost/easypost-go#210]
Can you please document the proper way to use the DateTime class? Or determine whether this is a bug?

My usage is in the context of ListOptions when listing batches, see my example below:
```go
	past := now.AddDate(0, -4, 0)
	now := time.Now().UTC()

	start := easypost.DateTimeFromTime(past)
	end := easypost.DateTimeFromTime(now)

	batches, err := client.ListBatches(
		&easypost.ListOptions{
			StartDateTime: &start,
			EndDateTime:   &end,
			PageSize:      100,
		},
	)
```

If we take a look at [ListBatchesWithContext](https://github.com/EasyPost/easypost-go/blob/2183713d0506fb2b3fb9949f29cb5b8d64e7a51b/batch.go#L77-L80), we can confirm it is receiving the values as expected:
```
&{  2023-11-23 19:39:51.435846 +0000 UTC 2024-03-23 19:39:51.435846 +0000 UTC 100}
```

However, it appears they are dropped in [convertOptsToURLValues](https://github.com/EasyPost/easypost-go/blob/2183713d0506fb2b3fb9949f29cb5b8d64e7a51b/client.go#L100-L103):
```
map[page_size:[100]]
```

Versions:
- go1.22.0 darwin/arm64
- [easypost-go/v4](https://github.com/EasyPost/easypost-go/releases/tag/v4.0.0)

Related: https://github.com/EasyPost/easypost-go/pull/184

**Comment by nwithan8** [comment]
Hello @s0nic7 , thanks for reaching out and bringing this to our attention!

After looking into it, it seems we missed implementing the ability for the `DateTime` class to be properly URL-encoded and included in HTTP payloads.

This is being fixed in https://github.com/EasyPost/easypost-go/pull/211 and will be included in our next release.

Thanks again!
