### ISSUE TITLE
Inconsistent naming between shipment.go internal objects

### ISSUE THREAD

**Issue by jontsai** [EasyPost/easypost-go#34]
In the [shipment.go](https://github.com/EasyPost/easypost-go/blob/66f8dddb8c4a12efa3c0f2ca0446406ed4beb36f/shipment.go) file, on a cursory inspection, the field names or keys for serializing/deserializing to/from JSON are inconsistently named against the class/objects: sometimes they match, sometimes they don’t.

I understand that there is no inherent requirement for the LHS key/field name to match with the RHS Golang class/object, but I believe it could lead to some confusion.

For example:

- `PostageLabel` :: `*PostageLabel` (https://github.com/EasyPost/easypost-go/blob/66f8dddb8c4a12efa3c0f2ca0446406ed4beb36f/shipment.go#L125)
- `Messages` :: `[]*CarrierMessage` (https://github.com/EasyPost/easypost-go/blob/66f8dddb8c4a12efa3c0f2ca0446406ed4beb36f/shipment.go#L126)
- `Options` :: *ShipmentOptions` (https://github.com/EasyPost/easypost-go/blob/66f8dddb8c4a12efa3c0f2ca0446406ed4beb36f/shipment.go#L127)

Since the RHS class names are full under our control, would it make sense to introduce some kind of common prefix or suffix to distinguish between custom objects, like `EasyPostOptions` (I know, ugly, but just putting it out there to start a discussion)

**Comment by thwarted** [comment]
They are already under the `easypost` package this file is defined in.  Because they are referenced in the same package, they are not absolute references. Outside of this package they are referenced as `easypost.PostageLabel`, `easypost.CarrierMessage`, and `easypost.ShipmentOptions` (unless the importing file has selected a new name to reference the imported package as).  While it doesn't necessarily reduce potential confusion, the go compiler won't let just anything be assigned to these fields, they need to be, in the case of `easypost.Shipment.PostageLabel`, an &easypost.PostageLabel{...}` and `easypost.Shipment.Messages` needs to be `[]*easypost.CarrierMessage`

Changing exported identifiers (those that start with capital letters) would influence the exposed API of this package also, which would have wider impact.

That the package name (`package easypost`) is different than the directory basename (`/easypost-go`) of the package is mildly more confusing, but this happens all the time, especially with versioned go modules.

**Comment by jontsai** [comment]
Thank you for the clarification @thwarted and @Justintime50 (on #33).

Since Golang is typed and compiled, and won’t allow illegal references, I believe it’s simplest to just leave the existing code as is, as the package is already namespaced, and introducing any common suffix or prefix would just make the code more unnecessarily verbose.

Closing as won’t fix.
